CREATE TABLE Rejets
(
	ligne ROWID,
	proprio VARCHAR(30),
	nom_table VARCHAR(30),
	contrainte VARCHAR(30)
);

ALTER TABLE PAYS
DISABLE CONSTRAINT FK_PAYS_CONTINENT;

select TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, VALIDATED FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'PAYS';

INSERT INTO Pays (nom, capitale, iso3, nomc)
VALUES ('IUT de Rangueil', 'Rangueil', 'UT3', 'IUT');

INSERT INTO Pays (nom, capitale, iso3, nomc)
VALUES ('IUT de Rodez', 'Rodez', 'UT1', 'IUT');

SELECT * FROM Pays;

SELECT * FROM Rejets;

ALTER TABLE Pays ENABLE CONSTRAINT FK_PAYS_CONTINENT EXCEPTIONS INTO REJETS;

SELECT ROWID, P.*
FROM Pays P WHERE ROWID IN (SELECT Ligne FROM Rejets);

DELETE FROM Pays P WHERE ROWID IN (SELECT Ligne FROM Rejets);

DELETE Rejets;

DROP TABLE Rejets;

ALTER TABLE Pays 
DROP CONSTRAINT FK_PAYS_CONTINENT;

ALTER TABLE Pays
ADD CONSTRAINT FK_PAYS_CONTINENT FOREIGN KEY (nomc) REFERENCES Continent(nom)
DEFERRABLE INITIALLY IMMEDIATE;

SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, DEFERRABLE, DEFERRED FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'PAYS';

ALTER TABLE PAYS MODIFY CONSTRAINT FK_PAYS_CONTINENT INITIALLY DEFERRED;

INSERT INTO Continent (nom)
VALUES ('IUT');